city/urls.py
from django.urls import path

from city import views

urlpatterns = [
    path('', views.detect_city, name='home'),
]

place/urls.py
from django.urls import path
from place import views

urlpatterns = [
    path('', views.index, name='place_list'),
    path('place_<int:id>/', views.index),
    path('add/', views.add, name='add_place'),
    path('edit/<int:id>/', views.add),
    path('upload_image/', views.upload_image),
    path('get_place_content/', views.get_place_content),
    path('get-full-info-modal/', views.get_full_info_modal),
    path('get-full-info/', views.get_full_info),
    path('delete/', views.delete, name='delete_place'),
    path('<str:category_alias>/', views.index),
]

yoweekend/urls.py
from django.contrib import admin
from django.urls import path, include

import event
import place.views
from event.views import get_full_info, get_full_info_modal, get_event_content
from sitemap.views import sitemap

urlpatterns = [
    path('obninsk/', event.views.redirect_from_old_urls),
    path('obninsk/event_<int:id>/', event.views.redirect_from_old_urls),
    path('obninsk/<str:category_alias>/', event.views.redirect_from_old_urls),
    
    path('admin/', admin.site.urls),
    path('', include('city.urls')),
    path('ajax/get-full-info/', get_full_info),
    path('ajax/get-full-info-modal/', get_full_info_modal),
    path('ajax/get-event-content/', get_event_content),
    path('usr/', include('allauth.urls')),
    path('usr/my-events/<str:is_draft>/', event.views.usr_events, name='user_events_is_draft'),
    path('usr/my-events/', event.views.usr_events, name='user_events'),
    path('usr/my-places/', place.views.usr_places, name='user_places'),
    path('usr/my-places/<str:is_draft>/', place.views.usr_places, name='user_places_is_draft'),
    path('event/add/', event.views.add, name='add_event'),
    path('event/edit/<int:id>/', event.views.add, name='edit_event'),
    path('event/delete/', event.views.delete, name='delete_event'),
    path('event/upload_image', event.views.upload_image, name='upload_event_image'),
    path('event/send-new-category/', event.views.send_new_category, name='send_new_category'),
    path('event/get-event-info-from-vk/', event.views.get_event_info_from_vk),
    path('sitemap.xml', sitemap, name='sitemap'),
    path('events/', include('event.urls')),
    path('places/', include('place.urls')),
]

handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

place/models.py
from django.db import models
from django.contrib.auth.models import User

from city.models import City


class PlaceCategory(models.Model):

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'place_categories'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('position', 'name')

    name = models.CharField(max_length=255, verbose_name=u'Название', null=False, blank=False, unique=True)
    alias = models.CharField(max_length=255, verbose_name=u'Алиас', null=False, blank=False, unique=True)
    meta_keywords = models.CharField(max_length=255, verbose_name=u'Ключевые слова', null=True, blank=True)
    meta_description = models.CharField(max_length=255, verbose_name=u'Описание', null=True, blank=True)
    position = models.IntegerField(default=0, verbose_name=u'Положение')
    hidden = models.BooleanField(default=False, verbose_name=u"Скрыть категорию")


#Сделать после миграции
#ALTER TABLE `places` CHANGE `description` `description` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;
class Place(models.Model):
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'places'
        verbose_name = 'Место'
        verbose_name_plural = 'Места'

    name = models.CharField(max_length=255, verbose_name=u'Название', null=False, blank=False)
    image_original = models.CharField(max_length=255, verbose_name=u'Оригинальное изображение', null=True, blank=True,
                                      default=None)
    image_preview = models.CharField(max_length=255, verbose_name=u'Оригинальное изображение', null=True, blank=True,
                                     default=None)
    link = models.CharField(max_length=255, verbose_name=u'Ссылка на сайт или группу в ВК', null=True, blank=True, default=None)
    city = models.ForeignKey(City, verbose_name=u'Город', on_delete=None, null=False, blank=False, default='')
    categories = models.ManyToManyField(PlaceCategory, verbose_name=u'Категории', default=None)
    address = models.CharField(max_length=255, verbose_name=u'Адрес', null=False, blank=False)
    timing = models.CharField(max_length=255, verbose_name=u'Расписание', null=True, blank=True)
    description = models.TextField(null=True, blank=True, verbose_name=u'Описание', default=None)
    isDraft = models.BooleanField(default=False, verbose_name=u'Черновик')
    isVkSend = models.BooleanField(default=False, verbose_name=u'Статус отправки в группу в ВК')
    user = models.ForeignKey(User, on_delete=None, blank=True)
    create_date = models.DateTimeField(verbose_name=u'Дата создания', default=None, null=True)
    update_date = models.DateTimeField(verbose_name=u'Дата обновления', default=None, null=True)

place/views.py
# -*- coding: UTF-8 -*-

import os

import re
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse, Http404
from django.shortcuts import redirect, render
from django.template.loader import get_template
from django.utils.html import linebreaks
from django.views.decorators.csrf import csrf_exempt

from app.views import getPreviewSize
from city.models import City
from place.forms import AddPlaceForm
from place.models import Place, PlaceCategory
from yoweekend.settings import BASE_DIR, EVENTS_PER_PAGE
from django.db.models.functions import datetime
from time import time
from PIL import Image


def index(request, id=None, category_alias=None):
    category = None
    city = City.detect_city(City, request=request)
    places = Place.objects.filter(city_id=city.id, isDraft=0)
    if category_alias is not None:
        places = places.filter(categories__alias=category_alias)
        try:
            category = PlaceCategory.objects.get(alias=category_alias)
        except PlaceCategory.DoesNotExist:
            raise Http404("Категория не найдена")
    places = places.order_by('name').all()[:EVENTS_PER_PAGE]
    place_info = None
    place_info_text = None
    if id is not None:
        place_info = Place.objects.get(id=id)
        if place_info:
            place_info_text = re.sub(
                r'((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w_-]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)',
                r'<a href="\1" target="_blank">\1</a>', place_info.description, flags=re.IGNORECASE)
            place_info_text = re.sub(r'<a href="([A-Za-z0-9_.]+@[A-Za-z0-9_.]+)"', r'<a href="mailto:\1"',
                                     place_info_text)
            place_info_text = linebreaks(place_info_text)

    #Определяем метатеги
    meta_tags = {}
    if category_alias is None and id is None:
        meta_tags['title'] = u'Все развлекательные места вашего города — %s — YOweekend.ru' % city.name
        meta_tags['description'] = u'Все развлекательные места и заведения в городе %s' % city.name
        meta_tags['keywords'] = u'развелечения в городе, развелкательные места, места, досуг, куда сходить, %s' % city.name

    if category_alias is not None:
        meta_tags['title'] = u'%s — Все места развлечений вашего города — %s — YOweekend.ru' % (category.name, city.name)
        if category.meta_description is not None:
            meta_tags['description'] = category.meta_description % (city.name)
        else:
            meta_tags['description'] = u'Все места развлечений в городе %s в категории %s' % (city.name, category.name)
        if category.meta_keywords is not None:
            meta_tags['keywords'] = category.meta_keywords % (city.name)
        else:
            meta_tags['keywords'] = u'развелечения в городе, развелкательные места, места, досуг, куда сходить, %s, %s' % (city.name, category.name)

    if id is not None:
        meta_tags['title'] = u'%s — Все места развлечений вашего города — %s — YOweekend.ru' % (place_info.name, city.name)
        meta_tags['description'] = place_info.description[:100]
        meta_tags['keywords'] = place_info.name

    response = render(request, 'place/index.html', {
        'city': city,
        'places': places,
        'category': category,
        'place_info': place_info,
        'place_info_text': place_info_text,
        'meta_tags': meta_tags
    })
    return response


def add(request, id=None):
    if not request.user.is_authenticated:
        return redirect('/')
    if id is None:
        title = u'Новое место'
    else:
        title = u'Редактирование места'
    flash_message = {}
    model = None
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        if id is not None:
            try:
                model = Place.objects.get(id=id, user_id=user.id)
            except:
                return redirect('/')
            form = AddPlaceForm(request.POST or None, instance=model)
        else:
            form = AddPlaceForm(request.POST or None)
        if form.is_valid():
            place_cont = form.save(commit=False)
            # Создаем папку для изображений
            directory = '/static/media/userimages/%s/' % user.id
            if not os.path.exists(BASE_DIR + directory):
                os.makedirs(BASE_DIR + directory)
            # Копируем основное изображение из временной папки
            source_filename, file_extension = os.path.splitext(form.cleaned_data['image_original'])
            _new_file_name = hex(int(time() * 10000000))[2:]
            _main_image = Image.open(BASE_DIR + form.cleaned_data['image_original'])
            _main_image.save(BASE_DIR + directory + _new_file_name + file_extension)
            place_cont.image_original = directory + _new_file_name + file_extension
            # КОНЕЦ скопировали основное изображение
            # Создаем превью 300 на 300 из превью, которое пришло из формы
            x1 = form.cleaned_data['x1']
            y1 = form.cleaned_data['y1']
            _preview_image = Image.open(BASE_DIR + form.cleaned_data['image_preview'])
            _preview_image = _preview_image.crop((x1, y1, x1 + 300, y1 + 300))
            _preview_image.save(BASE_DIR + directory + 'preview_' + _new_file_name + file_extension)
            place_cont.image_preview = directory + 'preview_' + _new_file_name + file_extension
            # КОНЕЦ сделали превью и скопировали его в нужную папку
            place_cont.user = user
            if place_cont.id is None:
                place_cont.create_date = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            else:
                place_cont.update_date = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            place_cont.save()
            place_cont.categories.clear()
            for c in form.cleaned_data['categories']:
                place_cont.categories.add(c)
            messages.add_message(request, messages.SUCCESS,
                                 'Ваше место успешно сохранено, теперь его видят пользователи в ленте.',
                                 extra_tags='SAVE_SUCCESS')
            return redirect('/places/edit/%s/' % place_cont.id)
        else:
            flash_message = {
                'class': 'warning',
                'title': 'Ошибка',
                'message': 'В форме есть ошибки. Исправьте их и повторите сохранение',
            }
    else:
        if id is None:
            form = AddPlaceForm(initial={
                'image_preview': '/static/img/temp_image.png',
                'image_original': '/static/img/temp_image.png',
                'x1': 0,
                'x2': 299,
                'y1': 0,
                'y2': 299,
            })
        else:
            try:
                model = Place.objects.get(id=id, user_id=request.user.id)
            except:
                return redirect('/')
            form = AddPlaceForm(initial={
                'x1': 0,
                'x2': 299,
                'y1': 0,
                'y2': 299,
            }, instance=model)
    return render(request, 'place/add.html', {
        'form': form,
        'flash_message': flash_message,
        'title': title,
        'model': model
    })


def upload_image(request):
    if request.is_ajax() and request.FILES['place_image']:
        image_file = request.FILES['place_image']
        source_filename, file_extension = os.path.splitext(image_file.name)
        if file_extension not in ['.jpg', '.png', '.jpeg']:
            return JsonResponse({
                'status': False,
                'textError': u'Вы можете загружать только файлы изображений с разрешениями png, jpg, jpeg.'
            })
        fs = FileSystemStorage()
        directory = '/static/media/temp/%s/' % (request.session.session_key)
        if not os.path.exists(BASE_DIR + directory):
            os.makedirs(BASE_DIR + directory)
        uid = hex(int(time() * 10000000))[2:]
        target_file_name = uid + file_extension
        target_uploaded_file_name = fs.save(BASE_DIR + directory + target_file_name, image_file)
        target_uploaded_file_path = fs.url(target_uploaded_file_name)
        if target_uploaded_file_path:
            source_image = Image.open('/' + target_uploaded_file_path)
            width, height = source_image.size
            options = getPreviewSize(width, height)
            preview_image = source_image.resize((options['width'], options['height']), Image.ANTIALIAS)
            preview_image.save(BASE_DIR + directory + 'preview_' + target_file_name)
            target_uploaded_file_path_preview = directory + 'preview_' + target_file_name
            return JsonResponse({
                'name': target_file_name,
                'size': image_file.size,
                'url': directory + target_file_name,
                'thumbnailUrl': target_uploaded_file_path_preview,
                'width': options['width'],
                'height': options['height'],
            })


def usr_places(request, is_draft=None):
    if not request.user.is_authenticated:
        return redirect('/')
    places = Place.objects.filter(user_id=request.user.id)
    if is_draft != None and is_draft == 'drafts':
        places = places.filter(isDraft=True)
    places = places.order_by('-name').all()

    return render(request, 'place/user_places.html', {
        'places': places,
        'is_draft': is_draft,
    })



@csrf_exempt
def get_place_content(request):
    city = City.detect_city(City, request=request)
    limit = int(request.POST.get('startFrom', 0))
    offset = int(request.POST.get('startFrom', 0)) + int(EVENTS_PER_PAGE)

    places = Place.objects.filter(city_id=city.id, isDraft=0)
    if request.POST.get('category') != 'None':
        places = places.filter(categories__alias=request.POST.get('category'))

place/templates/place/_full_info_modal.html
{% load staticfiles %}
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 full-info-modal">
    <img class="img-responsive" src="{{ data.image_preview }}">
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 full-info-modal">
    <div class="caption full-info-modal-caption">
        <span class="icon-panel">
            <a class="btn btn-default" href="https://vk.com/share.php?url=http://{{ request.META.SERVER_NAME }}/{{ data.city.alias }}/event_{{ data.id }}&title={{ data.name }}&image=http://{{ request.META.SERVER_NAME }}{% static data.image_original %}&noparse=true" target="_blank">
                Рассказать друзьям <i class="fa fa-share-alt"></i>
            </a>
        </span>
        {% if data.link %}
            <span class="link"><a href="{{ data.link }}" target="_blank">{{ data.link|truncatechars:30 }}</a></span>
        {% endif %}
        <span class="datetime">
             <strong class="strong-underline">Расписение работы:</strong><br />
       		{{ data.timing }}
        </span>
    </div>
</div>
<div class="clear"></div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 full-info-modal-intro">
    <span class="intro">{{ text|safe }}</span>
</div>
<div class="clear"></div>

place/templates/place/_place.html
{% load staticfiles %}

<div class="card col-lg-3 col-md-4 col-sm-4 col-xs-6">
    <div class="thumbnail">
        <div class="image-preview">
            <img src="{{ p.image_preview }}" data-full-img="{{ p.image_original }}" data-address="{{ p.city.name }}, {{ p.address }}" data-id="{{ p.id }}">
            {% if p.address  %}
                <span class="address"><a href="#" class="openMap" data-address="{{ p.city.name }}, {{ p.address }}" onclick="openMap($(this).attr('data-address'));return false;"><i class="fa fa-map-marker address-marker"></i><span class="address-text">{{ p.address }}</span></a></span>
            {% endif %}
        </div>
        <div class="caption">
            <span class="icon-panel">
                <a class="share-icon" href="https://vk.com/share.php?url=http://{{ request.META.SERVER_NAME }}/{{ p.city.alias }}/event_{{ p.id }}&title={{ p.name }}&image=http://{{ request.META.SERVER_NAME }}{{ p.image_original }}&noparse=true" target="_blank">
                    <i class="fa fa-share-alt"></i>
                </a>
            </span>
            <span class="name"><a href="/places/place_{{ p.id }}/" class="open-event-window" data-id="{{ p.id }}" onclick="showFullInfo($(this).attr('data-id'), '/places/get-full-info-modal/');return false;">{{ p.name|truncatechars:60 }}</a></span>
            {% if p.link %}
                <span class="link"><a href="{{ p.link }}" target="_blank">{{ p.link|truncatechars:30 }}</a></span>
            {% endif %}
            <span class="money"><strong class="strong-underline">Режим работы:</strong>
                {% if p.timing == None %}
                    Не указан
                {% else %}
                    {{ p.timing }}
                {% endif %}
            </span>
            <br>
            <span class="intro"><a href="#" class="showFullInfo" data-id="{{ p.id }}" onclick="showFullInfo($(this).attr('data-id'), '/places/get-full-info/');return false;">{{ p.description|truncatechars:100 }}</a></span>
        </div>
    </div>
</div>

place/templates/place/add.html
{% extends 'main.html' %}

{% load staticfiles %}
{% load common %}
{% load eventstags %}
{% load placecategoriestags %}

{% block meta_block %}
    <title>{{ title }} - Yoweekend.ru</title>
    <style>
        .sidebar .slimScrollDiv { display: block !important; }
    </style>
{% endblock %}

{% block users_scripts %}
    <script type="text/javascript" src="{% static 'libs/jquery-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/jquery-file-upload/js/jquery.iframe-transport.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/jquery-file-upload/js/jquery.fileupload.js' %}"></script>
    <link rel="stylesheet" href="{% static 'libs/jquery-file-upload/css/jquery.fileupload.css' %}">
    <script type="text/javascript" src="{% static 'js/add_place.js' %}?v=0001"></script>
{% endblock %}

{% block sidebar %}
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu sidebar-category-links places" data-widget="tree">
        <li class="header">Места</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="/places/"><span>Все категории</span></a></li>
        {% sidebarlist request %}
    </ul>
    <!-- /.sidebar-menu -->
{% endblock %}

{% block content %}
    {% if flash_message %}
        <div class="callout callout-{{ flash_message.class }}" style="">
            {{ flash_message.message }}
        </div>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
            {% if message.extra_tags == 'SAVE_SUCCESS' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
<form method="post" id="add_event_form">
    {% csrf_token %}
    <div class="form-group">
        <label>Фото</label>
        <div class="input-group">
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Выбрать файл</span>
                <!-- The file input field used as target for the file upload widget -->
                <input type="file" id="event-image" name="place_image" accept="image/*" data-url="/places/upload_image/">
            </span>
            <div class="img_preview">
                <img class="img-responsive object-image" src="{{ form.image_preview.value }}" data-real-width="{{ form.image_preview.value|getimagesize:'width' }}" data-real-height="{{ form.image_preview.value|getimagesize:'height' }}">
            </div>
        </div>
    </div>
    <div class="form-group {% if form.image_preview.errors %} has-error {% endif %}">
        {{ form.image_preview }}
        {% if form.image_preview.errors %}
            <p class="help-block help-block-error">{{ form.image_preview.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.image_original.errors %} has-error {% endif %}">
        {{ form.image_original }}
        {% if form.image_original.errors %}
            <p class="help-block help-block-error">{{ form.image_original.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.x1.errors %} has-error {% endif %}">
        {{ form.x1 }}
        {% if form.x1.errors %}
            <p class="help-block help-block-error">{{ form.x1.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.x2.errors %} has-error {% endif %}">
        {{ form.x2 }}
        {% if form.x2.errors %}
            <p class="help-block help-block-error">{{ form.x2.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.y1.errors %} has-error {% endif %}">
        {{ form.y1 }}
        {% if form.y1.errors %}
            <p class="help-block help-block-error">{{ form.y1.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.y2.errors %} has-error {% endif %}">
        {{ form.y2 }}
        {% if form.y2.errors %}
            <p class="help-block help-block-error">{{ form.y2.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.link.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.link.id_for_label }}">{{ form.link.label }}</label>
        {{ form.link }}
        <div class="clear"></div>
        {% if form.link.errors %}
            <p class="help-block help-block-error">{{ form.link.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.name.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
        {{ form.name }}
        {% if form.name.errors %}
            <p class="help-block help-block-error">{{ form.name.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.categories.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.categories.id_for_label }}">{{ form.categories.label }}</label>
        {{ form.categories }}
        {% if form.categories.errors %}
            <p class="help-block help-block-error">{{ form.categories.errors|first }}</p>
        {% endif %}
        <a href="#" data-toggle="modal" data-target="#add-new-category">Если вы не нашли свою категорию, нажмите на эту ссылку</a>
    </div>
    <div class="form-group {% if form.city.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
        {{ form.city }}
        {% if form.city.errors %}
            <p class="help-block help-block-error">{{ form.city.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.address.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
        {{ form.address }}
        {% if form.address.errors %}
            <p class="help-block help-block-error">{{ form.address.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group {% if form.timing.errors %} has-error {% endif %}">
        <label class="control-label" for="{{ form.timing.id_for_label }}">{{ form.timing.label }}</label>
        {{ form.timing }}
        {% if form.timing.errors %}
            <p class="help-block help-block-error">{{ form.timing.errors|first }}</p>
        {% endif %}
    </div>
    <div class="form-group">
        <label class="control-label" for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
        {{ form.description }}
    </div>
    <div class="form-group">
            <label class="draft-checkbox-label" for="{{ form.isDraft.id_for_label }}">
                {{ form.isDraft }}
                {{ form.isDraft.label }}
            </label>
        </div>
    <div class="form-group col-lg-2 col-md-2 col-sm-2 col-xs-6" style="padding-left: 0; ">
        <button type="submit" class="btn btn-block btn-primary btn-flat">Сохранить</button>
    </div>
</form>
<div class="modal fade in" id="add-new-category">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Запрос на добавление категории</h4>
            </div>
            <div class="modal-body">
                <div class="callout" style="display: none;">
                        <h4><i class="fa fa-info"></i></h4>
                        <span>dfgdfg</span>
                </div>
                <form>
                    <div class="form-group category-name required">
                        <label class="control-label" for="category-name">Введите название предлагаемой категории</label>
                        <input type="text" class="form-control">
                        <p class="help-block help-block-error"></p>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-left" id="send-new-category">Отправить</button>
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
    <script type="text/javascript">
        window.onload = function (ev) {
                $('#event-image').fileupload({"maxFileSize":2000000,"dataType":"json","url":"/places/upload_image/"});
                $('#event-image').on('fileuploaddone', function(e, data) {
                                if(typeof(data.result.status) != undefined && data.result.status == false) {
                                    show_info_modal("Ошибка!", data.result.textError);
                                } else {
                                    $(".field-event-image_original").removeClass("has-error");
                                    $(".field-event-image_original p").empty();
                                    $("#id_image_original").val(data.result.url);
                                    $("#id_image_preview").val(data.result.thumbnailUrl);
                                    $(".object-image").imgAreaSelect( {remove: true} );
                                    $(".object-image").attr("src", data.result.thumbnailUrl).imgAreaSelect({
                                        handles: true,
                                        onSelectEnd: setImgCoordinates,
                                        onInit: setImgCoordinates,
                                        minWidth: 299,
                                        minHeight: 299,
                                        maxWidth: 300,
                                        maxHeight: 300,
                                        show: true,
                                        imageHeight: data.result.height,
                                        imageWidth: data.result.width,
                                        x1: 0,
                                        x2: 298,
                                        y1: 0,
                                        y2: 298,
                                    });
                                }
                            });
                $('#event-image').on('fileuploadfail', function(e, data) {
                    console.log(e);
                    console.log(data);
                    show_info_modal("Ошибка!", "В процессе загрузки файла произошла ошибка");
                });
        }
    </script>
{% endblock %}

place/templates/place/places.html
{% load common %}
{% if from_ajax != True %}
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 date-label-area">
        <div class="date-label">
            {% if category == None %}
                Все категории
                <input type="hidden" name="place_category" value="None">
            {% else %}
                {{ category.name }}
                <input type="hidden" name="place_category" value="{{ category.alias }}">
            {% endif %}
        </div>
    </div>
{% endif %}
{% for p in places %}
    {% include 'place/_place.html' with p=p %}
{% endfor %}

place/templates/place/user_places.html
{% extends 'main.html' %}

{% load placecategoriestags %}

{% block meta_block %}
    <title>Мои места — Yoweekend.ru</title>
    <style>
        .sidebar .slimScrollDiv { display: block !important; }
    </style>
{% endblock %}

{% block sidebar %}
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu sidebar-category-links places" data-widget="tree">
        <li class="header">Места</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="/places/"><span>Все категории</span></a></li>
        {% sidebarlist request %}
    </ul>
    <!-- /.sidebar-menu -->
{% endblock %}

{% block content %}
<div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 add-event-not-register">
    <button type="button" class="btn btn-block btn-success btn-sm"
            onclick="window.location.href = '{% url 'add_place' %}'">
        <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Добавить место
    </button>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 isDraftLink">
    <label class='draft-checkbox-label'>
        {% if is_draft %}
            <input type="checkbox" class="minimal" checked > <span>Показать только черновики</span>
        {% else %}
            <input type="checkbox" class="minimal"> <span>Показать только черновики</span>
        {% endif %}
    </label>
</div>
<div class="clear" style="clear: both"></div>
    {% include 'place/places.html' %}
{% endblock %}